# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux_64_cross_target_platformlinux-64ctng_vendorconda_cos6tripletx86_64-conda-linux-gnu:
        CONFIG: linux_64_cross_target_platformlinux-64ctng_vendorconda_cos6tripletx86_64-conda-linux-gnu
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_target_platformlinux-aarch64ctng_vendorconda_cos7tripletaarch64-conda-linux-gnu:
        CONFIG: linux_64_cross_target_platformlinux-aarch64ctng_vendorconda_cos7tripletaarch64-conda-linux-gnu
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_target_platformlinux-ppc64lectng_vendorconda_cos7tripletpowerpc64le-conda-linux-gnu:
        CONFIG: linux_64_cross_target_platformlinux-ppc64lectng_vendorconda_cos7tripletpowerpc64le-conda-linux-gnu
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_target_platformlinux-s390xctng_vendorconda_cos7triplets390x-conda-linux-gnu:
        CONFIG: linux_64_cross_target_platformlinux-s390xctng_vendorconda_cos7triplets390x-conda-linux-gnu
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_cross_target_platformwin-64ctng_vendornonetripletx86_64-w64-mingw32:
        CONFIG: linux_64_cross_target_platformwin-64ctng_vendornonetripletx86_64-w64-mingw32
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_s390x_cross_target_platformlinux-64ctng_vendorconda_cos6tripletx86_64-conda-linux-gnu:
        CONFIG: linux_s390x_cross_target_platformlinux-64ctng_vendorconda_cos6tripletx86_64-conda-linux-gnu
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_s390x_cross_target_platformlinux-aarch64ctng_vendorconda_cos7tripletaarch64-conda-linux-gnu:
        CONFIG: linux_s390x_cross_target_platformlinux-aarch64ctng_vendorconda_cos7tripletaarch64-conda-linux-gnu
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_s390x_cross_target_platformlinux-ppc64lectng_vendorconda_cos7tripletpowerpc64le-conda-linux-gnu:
        CONFIG: linux_s390x_cross_target_platformlinux-ppc64lectng_vendorconda_cos7tripletpowerpc64le-conda-linux-gnu
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_s390x_cross_target_platformlinux-s390xctng_vendorconda_cos7triplets390x-conda-linux-gnu:
        CONFIG: linux_s390x_cross_target_platformlinux-s390xctng_vendorconda_cos7triplets390x-conda-linux-gnu
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_s390x_cross_target_platformwin-64ctng_vendornonetripletx86_64-w64-mingw32:
        CONFIG: linux_s390x_cross_target_platformwin-64ctng_vendornonetripletx86_64-w64-mingw32
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      win_64_cross_target_platformwin-64ctng_vendornonetripletx86_64-w64-mingw32:
        CONFIG: win_64_cross_target_platformwin-64ctng_vendornonetripletx86_64-w64-mingw32
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
  timeoutInMinutes: 360
  variables: {}

  steps:
  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export flow_run_id=azure_$(Build.BuildNumber).$(System.JobAttempt)
        export remote_url=$(Build.Repository.Uri)
        export sha=$(Build.SourceVersion)
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)